name: AHT_human_intervention_import
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - -r requirements.txt
  - uwsgi
  - openai